spring.datasource.url=jdbc:postgresql://localhost:5432/spaceweather
spring.datasource.username=postgres
spring.datasource.password=Admin4321

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
